# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abac04f889d5225720f8270669874cb19200728bce3077dfee9ee4d451ac31c80ad3694541e3961d09b1ae7fd0dccdc48f7888453651cf774e068e8890a87f06

test:
  secret_key_base: a9eee5e19620370c5a4d6f4b8097a2c62a9adc8a87c74a7b1cd3d03c5de44198391d4a08774ffcad9bbbb5c397bc006fa689242df4c6946e55c7bd48137172f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
